// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface DelegationTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.DelegationToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .alluxio.grpc.file.DelegationTokenIdentifier identifier = 1;</code>
   */
  boolean hasIdentifier();
  /**
   * <code>optional .alluxio.grpc.file.DelegationTokenIdentifier identifier = 1;</code>
   */
  alluxio.grpc.DelegationTokenIdentifier getIdentifier();
  /**
   * <code>optional .alluxio.grpc.file.DelegationTokenIdentifier identifier = 1;</code>
   */
  alluxio.grpc.DelegationTokenIdentifierOrBuilder getIdentifierOrBuilder();

  /**
   * <code>optional bytes password = 2;</code>
   */
  boolean hasPassword();
  /**
   * <code>optional bytes password = 2;</code>
   */
  com.google.protobuf.ByteString getPassword();
}
