// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public final class FileSystemMasterProto {
  private FileSystemMasterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CheckConsistencyPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CompleteFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_OpenFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateDirectoryPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CreateFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DeletePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DeletePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FreePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FreePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetStatusPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DelegationTokenIdentifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DelegationTokenIdentifier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_DelegationToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_DelegationToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetDelegationTokenPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetDelegationTokenPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetDelegationTokenPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetDelegationTokenPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenewDelegationTokenPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenewDelegationTokenPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenewDelegationTokenPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenewDelegationTokenPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CancelDelegationTokenPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CancelDelegationTokenPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_CancelDelegationTokenPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_CancelDelegationTokenPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ExistsPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ExistsPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SyncPointInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SyncPointInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetSyncPathListPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetSyncPathListPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ListStatusPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_LoadMetadataPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PAclEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PAclEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PAcl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PAcl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileBlockInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileBlockInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetMountTablePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPointInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPointInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemCommandOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PersistCommandOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_PersistFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_PersistFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_RenamePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_RenamePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAttributePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_SetAclPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_SetAclPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StartSyncPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_StopSyncPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UnmountPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UnmountPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UfsInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UfsInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_UpdateUfsModePRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetFileInfoPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_file_GetUfsInfoPRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035grpc/file_system_master.proto\022\021alluxio" +
      ".grpc.file\032\021grpc/common.proto\032\023grpc/fsco" +
      "mmon.proto\032%proto/security/capability_pr" +
      "oto.proto\"q\n\036FileSystemMasterCommonPOpti" +
      "ons\022\026\n\016syncIntervalMs\030\001 \001(\003\022\013\n\003ttl\030\002 \001(\003" +
      "\022*\n\tttlAction\030\003 \001(\0162\027.alluxio.grpc.TtlAc" +
      "tion\"6\n\031CheckConsistencyPResponse\022\031\n\021inc" +
      "onsistentPaths\030\001 \003(\t\"d\n\030CheckConsistency" +
      "POptions\022H\n\rcommonOptions\030\001 \001(\01321.alluxi" +
      "o.grpc.file.FileSystemMasterCommonPOptio" +
      "ns\"f\n\030CheckConsistencyPRequest\022\014\n\004path\030\001" +
      " \001(\t\022<\n\007options\030\002 \001(\0132+.alluxio.grpc.fil" +
      "e.CheckConsistencyPOptions\"\027\n\025CompleteFi" +
      "lePResponse\"s\n\024CompleteFilePOptions\022\021\n\tu" +
      "fsLength\030\001 \001(\003\022H\n\rcommonOptions\030\002 \001(\01321." +
      "alluxio.grpc.file.FileSystemMasterCommon" +
      "POptions\"^\n\024CompleteFilePRequest\022\014\n\004path" +
      "\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio.grpc.f" +
      "ile.CompleteFilePOptions\"\207\002\n\020OpenFilePOp" +
      "tions\022.\n\010readType\030\001 \001(\0162\034.alluxio.grpc.f" +
      "ile.ReadPType\022\035\n\025maxUfsReadConcurrency\030\002" +
      " \001(\005\022\036\n\026fileReadLocationPolicy\030\003 \001(\t\022\035\n\025" +
      "hashingNumberOfShards\030\004 \001(\005\022H\n\rcommonOpt" +
      "ions\030\005 \001(\01321.alluxio.grpc.file.FileSyste" +
      "mMasterCommonPOptions\022\033\n\022skipTransformat" +
      "ion\030\351\007 \001(\010\"\032\n\030CreateDirectoryPResponse\"\340" +
      "\001\n\027CreateDirectoryPOptions\022\021\n\trecursive\030" +
      "\001 \001(\010\022\023\n\013allowExists\030\002 \001(\010\022!\n\004mode\030\003 \001(\013" +
      "2\023.alluxio.grpc.PMode\0220\n\twriteType\030\004 \001(\016" +
      "2\035.alluxio.grpc.file.WritePType\022H\n\rcommo" +
      "nOptions\030\005 \001(\01321.alluxio.grpc.file.FileS" +
      "ystemMasterCommonPOptions\"d\n\027CreateDirec" +
      "toryPRequest\022\014\n\004path\030\001 \001(\t\022;\n\007options\030\002 " +
      "\001(\0132*.alluxio.grpc.file.CreateDirectoryP" +
      "Options\"\025\n\023CreateFilePResponse\"\336\002\n\022Creat" +
      "eFilePOptions\022\026\n\016blockSizeBytes\030\001 \001(\003\022\021\n" +
      "\trecursive\030\002 \001(\010\022!\n\004mode\030\003 \001(\0132\023.alluxio" +
      ".grpc.PMode\022\026\n\016replicationMax\030\004 \001(\005\022\026\n\016r" +
      "eplicationMin\030\005 \001(\005\022\032\n\022replicationDurabl" +
      "e\030\006 \001(\005\022\037\n\027fileWriteLocationPolicy\030\007 \001(\t" +
      "\022\021\n\twriteTier\030\010 \001(\005\0220\n\twriteType\030\t \001(\0162\035" +
      ".alluxio.grpc.file.WritePType\022H\n\rcommonO" +
      "ptions\030\n \001(\01321.alluxio.grpc.file.FileSys" +
      "temMasterCommonPOptions\"Z\n\022CreateFilePRe" +
      "quest\022\014\n\004path\030\001 \001(\t\0226\n\007options\030\002 \001(\0132%.a" +
      "lluxio.grpc.file.CreateFilePOptions\"\021\n\017D" +
      "eletePResponse\"\225\001\n\016DeletePOptions\022\021\n\trec" +
      "ursive\030\001 \001(\010\022\023\n\013alluxioOnly\030\002 \001(\010\022\021\n\tunc" +
      "hecked\030\003 \001(\010\022H\n\rcommonOptions\030\004 \001(\01321.al" +
      "luxio.grpc.file.FileSystemMasterCommonPO" +
      "ptions\"R\n\016DeletePRequest\022\014\n\004path\030\001 \001(\t\0222" +
      "\n\007options\030\002 \001(\0132!.alluxio.grpc.file.Dele" +
      "tePOptions\"\017\n\rFreePResponse\"{\n\014FreePOpti" +
      "ons\022\021\n\trecursive\030\001 \001(\010\022\016\n\006forced\030\002 \001(\010\022H" +
      "\n\rcommonOptions\030\003 \001(\01321.alluxio.grpc.fil" +
      "e.FileSystemMasterCommonPOptions\"N\n\014Free" +
      "PRequest\022\014\n\004path\030\001 \001(\t\0220\n\007options\030\002 \001(\0132" +
      "\037.alluxio.grpc.file.FreePOptions\"+\n\035GetN" +
      "ewBlockIdForFilePResponse\022\n\n\002id\030\001 \001(\003\"h\n" +
      "\034GetNewBlockIdForFilePOptions\022H\n\rcommonO" +
      "ptions\030\001 \001(\01321.alluxio.grpc.file.FileSys" +
      "temMasterCommonPOptions\"n\n\034GetNewBlockId" +
      "ForFilePRequest\022\014\n\004path\030\001 \001(\t\022@\n\007options" +
      "\030\002 \001(\0132/.alluxio.grpc.file.GetNewBlockId" +
      "ForFilePOptions\"C\n\022GetStatusPResponse\022-\n" +
      "\010fileInfo\030\001 \001(\0132\033.alluxio.grpc.file.File" +
      "Info\"\306\001\n\021GetStatusPOptions\022>\n\020loadMetada" +
      "taType\030\001 \001(\0162$.alluxio.grpc.file.LoadMet" +
      "adataPType\022H\n\rcommonOptions\030\002 \001(\01321.allu" +
      "xio.grpc.file.FileSystemMasterCommonPOpt" +
      "ions\022\'\n\naccessMode\030\350\007 \001(\0162\022.alluxio.grpc" +
      ".Bits\"X\n\021GetStatusPRequest\022\014\n\004path\030\001 \001(\t" +
      "\0225\n\007options\030\002 \001(\0132$.alluxio.grpc.file.Ge" +
      "tStatusPOptions\"\236\001\n\031DelegationTokenIdent" +
      "ifier\022\r\n\005owner\030\001 \001(\t\022\017\n\007renewer\030\002 \001(\t\022\020\n" +
      "\010realUser\030\003 \001(\t\022\021\n\tissueDate\030\004 \001(\003\022\017\n\007ma" +
      "xDate\030\005 \001(\003\022\026\n\016sequenceNumber\030\006 \001(\003\022\023\n\013m" +
      "asterKeyId\030\007 \001(\003\"e\n\017DelegationToken\022@\n\ni" +
      "dentifier\030\001 \001(\0132,.alluxio.grpc.file.Dele" +
      "gationTokenIdentifier\022\020\n\010password\030\002 \001(\014\"" +
      "P\n\033GetDelegationTokenPResponse\0221\n\005token\030" +
      "\001 \001(\0132\".alluxio.grpc.file.DelegationToke" +
      "n\"-\n\032GetDelegationTokenPRequest\022\017\n\007renew" +
      "er\030\001 \001(\t\"9\n\035RenewDelegationTokenPRespons" +
      "e\022\030\n\020expirationTimeMs\030\001 \001(\003\"Q\n\034RenewDele" +
      "gationTokenPRequest\0221\n\005token\030\001 \001(\0132\".all" +
      "uxio.grpc.file.DelegationToken\" \n\036Cancel" +
      "DelegationTokenPResponse\"R\n\035CancelDelega" +
      "tionTokenPRequest\0221\n\005token\030\001 \001(\0132\".allux" +
      "io.grpc.file.DelegationToken\"\232\001\n\016ExistsP" +
      "Options\022>\n\020loadMetadataType\030\001 \001(\0162$.allu" +
      "xio.grpc.file.LoadMetadataPType\022H\n\rcommo" +
      "nOptions\030\002 \001(\01321.alluxio.grpc.file.FileS" +
      "ystemMasterCommonPOptions\"]\n\rSyncPointIn" +
      "fo\022\024\n\014syncPointUri\030\001 \001(\t\0226\n\nsyncStatus\030\002" +
      " \001(\0162\".alluxio.grpc.file.SyncPointStatus" +
      "\"O\n\030GetSyncPathListPResponse\0223\n\tsyncPath" +
      "s\030\001 \003(\0132 .alluxio.grpc.file.SyncPointInf" +
      "o\"\031\n\027GetSyncPathListPRequest\"E\n\023ListStat" +
      "usPResponse\022.\n\tfileInfos\030\001 \003(\0132\033.alluxio" +
      ".grpc.file.FileInfo\"\315\001\n\022ListStatusPOptio" +
      "ns\022\032\n\022loadDirectChildren\030\001 \001(\010\022>\n\020loadMe" +
      "tadataType\030\002 \001(\0162$.alluxio.grpc.file.Loa" +
      "dMetadataPType\022H\n\rcommonOptions\030\003 \001(\01321." +
      "alluxio.grpc.file.FileSystemMasterCommon" +
      "POptions\022\021\n\trecursive\030\004 \001(\010\"Z\n\022ListStatu" +
      "sPRequest\022\014\n\004path\030\001 \001(\t\0226\n\007options\030\002 \001(\013" +
      "2%.alluxio.grpc.file.ListStatusPOptions\"" +
      "#\n\025LoadMetadataPResponse\022\n\n\002id\030\001 \001(\003\"\324\001\n" +
      "\024LoadMetadataPOptions\022\021\n\trecursive\030\001 \001(\010" +
      "\022\027\n\017createAncestors\030\002 \001(\010\022F\n\022loadDescend" +
      "antType\030\003 \001(\0162*.alluxio.grpc.fscommon.Lo" +
      "adDescendantPType\022H\n\rcommonOptions\030\004 \001(\013" +
      "21.alluxio.grpc.file.FileSystemMasterCom" +
      "monPOptions\"a\n\024LoadMetadataPRequest\022\017\n\007u" +
      "fsPath\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio." +
      "grpc.file.LoadMetadataPOptions\"\217\001\n\tPAclE" +
      "ntry\022.\n\004type\030\001 \001(\0162 .alluxio.grpc.file.P" +
      "AclEntryType\022\017\n\007subject\030\002 \001(\t\022.\n\007actions" +
      "\030\003 \003(\0162\035.alluxio.grpc.file.PAclAction\022\021\n" +
      "\tisDefault\030\004 \001(\010\"\222\001\n\004PAcl\022\r\n\005owner\030\001 \001(\t" +
      "\022\023\n\013owningGroup\030\002 \001(\t\022-\n\007entries\030\003 \003(\0132\034" +
      ".alluxio.grpc.file.PAclEntry\022\014\n\004mode\030\004 \001" +
      "(\005\022\021\n\tisDefault\030\005 \001(\010\022\026\n\016isDefaultEmpty\030" +
      "\006 \001(\010\"\235\001\n\rFileBlockInfo\022*\n\tblockInfo\030\001 \001" +
      "(\0132\027.alluxio.grpc.BlockInfo\022\016\n\006offset\030\002 " +
      "\001(\003\0224\n\014ufsLocations\030\003 \003(\0132\036.alluxio.grpc" +
      ".WorkerNetAddress\022\032\n\022ufsStringLocations\030" +
      "\004 \003(\t\"\221\006\n\010FileInfo\022\016\n\006fileId\030\001 \001(\003\022\014\n\004na" +
      "me\030\002 \001(\t\022\014\n\004path\030\003 \001(\t\022\017\n\007ufsPath\030\004 \001(\t\022" +
      "\016\n\006length\030\005 \001(\003\022\026\n\016blockSizeBytes\030\006 \001(\003\022" +
      "\026\n\016creationTimeMs\030\007 \001(\003\022\021\n\tcompleted\030\010 \001" +
      "(\010\022\016\n\006folder\030\t \001(\010\022\016\n\006pinned\030\n \001(\010\022\021\n\tca" +
      "cheable\030\013 \001(\010\022\021\n\tpersisted\030\014 \001(\010\022\020\n\010bloc" +
      "kIds\030\r \003(\003\022\036\n\026lastModificationTimeMs\030\016 \001" +
      "(\003\022\013\n\003ttl\030\017 \001(\003\022\r\n\005owner\030\020 \001(\t\022\r\n\005group\030" +
      "\021 \001(\t\022\014\n\004mode\030\022 \001(\005\022\030\n\020persistenceState\030" +
      "\023 \001(\t\022\022\n\nmountPoint\030\024 \001(\010\0228\n\016fileBlockIn" +
      "fos\030\025 \003(\0132 .alluxio.grpc.file.FileBlockI" +
      "nfo\022*\n\tttlAction\030\026 \001(\0162\027.alluxio.grpc.Tt" +
      "lAction\022\017\n\007mountId\030\027 \001(\003\022\033\n\023inAlluxioPer" +
      "centage\030\030 \001(\005\022\032\n\022inMemoryPercentage\030\031 \001(" +
      "\005\022\026\n\016ufsFingerprint\030\032 \001(\t\022$\n\003acl\030\033 \001(\0132\027" +
      ".alluxio.grpc.file.PAcl\022+\n\ndefaultAcl\030\034 " +
      "\001(\0132\027.alluxio.grpc.file.PAcl\022\026\n\016replicat" +
      "ionMax\030\035 \001(\005\022\026\n\016replicationMin\030\036 \001(\005\0227\n\n" +
      "capability\030\353\007 \001(\0132\".alluxio.proto.securi" +
      "ty.Capability\022\022\n\tencrypted\030\354\007 \001(\010\"\020\n\016Mou" +
      "ntPResponse\"\364\001\n\rMountPOptions\022\020\n\010readOnl" +
      "y\030\001 \001(\010\022D\n\nproperties\030\002 \003(\01320.alluxio.gr" +
      "pc.file.MountPOptions.PropertiesEntry\022\016\n" +
      "\006shared\030\003 \001(\010\022H\n\rcommonOptions\030\004 \001(\01321.a" +
      "lluxio.grpc.file.FileSystemMasterCommonP" +
      "Options\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"h\n\rMountPRequest\022\023\n\013a" +
      "lluxioPath\030\001 \001(\t\022\017\n\007ufsPath\030\002 \001(\t\0221\n\007opt" +
      "ions\030\003 \001(\0132 .alluxio.grpc.file.MountPOpt" +
      "ions\"\300\001\n\026GetMountTablePResponse\022O\n\013mount" +
      "Points\030\001 \003(\0132:.alluxio.grpc.file.GetMoun" +
      "tTablePResponse.MountPointsEntry\032U\n\020Moun" +
      "tPointsEntry\022\013\n\003key\030\001 \001(\t\0220\n\005value\030\002 \001(\013" +
      "2!.alluxio.grpc.file.MountPointInfo:\0028\001\"" +
      "\027\n\025GetMountTablePRequest\"\205\002\n\016MountPointI" +
      "nfo\022\016\n\006ufsUri\030\001 \001(\t\022\017\n\007ufsType\030\002 \001(\t\022\034\n\020" +
      "ufsCapacityBytes\030\003 \001(\003:\002-1\022\030\n\014ufsUsedByt" +
      "es\030\004 \001(\003:\002-1\022\020\n\010readOnly\030\005 \001(\010\022E\n\nproper" +
      "ties\030\006 \003(\01321.alluxio.grpc.file.MountPoin" +
      "tInfo.PropertiesEntry\022\016\n\006shared\030\007 \001(\010\0321\n" +
      "\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"\\\n\030FileSystemCommandOptions\022@\n\016" +
      "persistOptions\030\001 \001(\0132(.alluxio.grpc.file" +
      ".PersistCommandOptions\"M\n\025PersistCommand" +
      "Options\0224\n\014persistFiles\030\001 \003(\0132\036.alluxio." +
      "grpc.file.PersistFile\"/\n\013PersistFile\022\016\n\006" +
      "fileId\030\001 \001(\003\022\020\n\010blockIds\030\002 \003(\003\"\210\001\n\021FileS" +
      "ystemCommand\022.\n\013commandType\030\001 \001(\0162\031.allu" +
      "xio.grpc.CommandType\022C\n\016commandOptions\030\002" +
      " \001(\0132+.alluxio.grpc.file.FileSystemComma" +
      "ndOptions\"\021\n\017RenamePResponse\"Z\n\016RenamePO" +
      "ptions\022H\n\rcommonOptions\030\001 \001(\01321.alluxio." +
      "grpc.file.FileSystemMasterCommonPOptions" +
      "\"c\n\016RenamePRequest\022\014\n\004path\030\001 \001(\t\022\017\n\007dstP" +
      "ath\030\002 \001(\t\0222\n\007options\030\003 \001(\0132!.alluxio.grp" +
      "c.file.RenamePOptions\"\027\n\025SetAttributePRe" +
      "sponse\"\300\002\n\024SetAttributePOptions\022\016\n\006pinne" +
      "d\030\001 \001(\010\022\013\n\003ttl\030\002 \001(\003\022*\n\tttlAction\030\003 \001(\0162" +
      "\027.alluxio.grpc.TtlAction\022\021\n\tpersisted\030\004 " +
      "\001(\010\022\r\n\005owner\030\005 \001(\t\022\r\n\005group\030\006 \001(\t\022!\n\004mod" +
      "e\030\007 \001(\0132\023.alluxio.grpc.PMode\022\021\n\trecursiv" +
      "e\030\010 \001(\010\022\026\n\016replicationMax\030\t \001(\005\022\026\n\016repli" +
      "cationMin\030\n \001(\005\022H\n\rcommonOptions\030\013 \001(\01321" +
      ".alluxio.grpc.file.FileSystemMasterCommo" +
      "nPOptions\"^\n\024SetAttributePRequest\022\014\n\004pat" +
      "h\030\001 \001(\t\0228\n\007options\030\002 \001(\0132\'.alluxio.grpc." +
      "file.SetAttributePOptions\"\021\n\017SetAclPResp" +
      "onse\"m\n\016SetAclPOptions\022H\n\rcommonOptions\030" +
      "\001 \001(\01321.alluxio.grpc.file.FileSystemMast" +
      "erCommonPOptions\022\021\n\trecursive\030\002 \001(\010\"\262\001\n\016" +
      "SetAclPRequest\022\014\n\004path\030\001 \001(\t\022/\n\006action\030\002" +
      " \001(\0162\037.alluxio.grpc.file.SetAclAction\022-\n" +
      "\007entries\030\003 \003(\0132\034.alluxio.grpc.file.PAclE" +
      "ntry\0222\n\007options\030\004 \001(\0132!.alluxio.grpc.fil" +
      "e.SetAclPOptions\"#\n!ScheduleAsyncPersist" +
      "encePResponse\"l\n ScheduleAsyncPersistenc" +
      "ePOptions\022H\n\rcommonOptions\030\001 \001(\01321.allux" +
      "io.grpc.file.FileSystemMasterCommonPOpti" +
      "ons\"v\n ScheduleAsyncPersistencePRequest\022" +
      "\014\n\004path\030\001 \001(\t\022D\n\007options\030\002 \001(\01323.alluxio" +
      ".grpc.file.ScheduleAsyncPersistencePOpti" +
      "ons\"\024\n\022StartSyncPResponse\"]\n\021StartSyncPO" +
      "ptions\022H\n\rcommonOptions\030\001 \001(\01321.alluxio." +
      "grpc.file.FileSystemMasterCommonPOptions" +
      "\"X\n\021StartSyncPRequest\022\014\n\004path\030\001 \001(\t\0225\n\007o" +
      "ptions\030\002 \001(\0132$.alluxio.grpc.file.StartSy" +
      "ncPOptions\"\023\n\021StopSyncPResponse\"\\\n\020StopS" +
      "yncPOptions\022H\n\rcommonOptions\030\001 \001(\01321.all" +
      "uxio.grpc.file.FileSystemMasterCommonPOp" +
      "tions\"V\n\020StopSyncPRequest\022\014\n\004path\030\001 \001(\t\022" +
      "4\n\007options\030\002 \001(\0132#.alluxio.grpc.file.Sto" +
      "pSyncPOptions\"\022\n\020UnmountPResponse\"[\n\017Unm" +
      "ountPOptions\022H\n\rcommonOptions\030\001 \001(\01321.al" +
      "luxio.grpc.file.FileSystemMasterCommonPO" +
      "ptions\"[\n\017UnmountPRequest\022\023\n\013alluxioPath" +
      "\030\001 \001(\t\0223\n\007options\030\002 \001(\0132\".alluxio.grpc.f" +
      "ile.UnmountPOptions\"L\n\007UfsInfo\022\013\n\003uri\030\001 " +
      "\001(\t\0224\n\nproperties\030\002 \001(\0132 .alluxio.grpc.f" +
      "ile.MountPOptions\"\030\n\026UpdateUfsModePRespo" +
      "nse\"E\n\025UpdateUfsModePOptions\022,\n\007ufsMode\030" +
      "\001 \001(\0162\033.alluxio.grpc.file.UfsPMode\"c\n\025Up" +
      "dateUfsModePRequest\022\017\n\007ufsPath\030\001 \001(\t\0229\n\007" +
      "options\030\002 \001(\0132(.alluxio.grpc.file.Update" +
      "UfsModePOptions\"U\n\034FileSystemHeartbeatPR" +
      "esponse\0225\n\007command\030\001 \001(\0132$.alluxio.grpc." +
      "file.FileSystemCommand\"@\n\033FileSystemHear" +
      "tbeatPOptions\022!\n\031persistedFileFingerprin" +
      "ts\030\001 \003(\t\"\210\001\n\033FileSystemHeartbeatPRequest" +
      "\022\020\n\010workerId\030\001 \001(\003\022\026\n\016persistedFiles\030\002 \003" +
      "(\003\022?\n\007options\030\003 \001(\0132..alluxio.grpc.file." +
      "FileSystemHeartbeatPOptions\"E\n\024GetFileIn" +
      "foPResponse\022-\n\010fileInfo\030\001 \001(\0132\033.alluxio." +
      "grpc.file.FileInfo\"\025\n\023GetFileInfoPOption" +
      "s\"^\n\023GetFileInfoPRequest\022\016\n\006fileId\030\001 \001(\003" +
      "\0227\n\007options\030\002 \001(\0132&.alluxio.grpc.file.Ge" +
      "tFileInfoPOptions\"2\n\031GetPinnedFileIdsPRe" +
      "sponse\022\025\n\rpinnedFileIds\030\001 \003(\003\"\032\n\030GetPinn" +
      "edFileIdsPOptions\"X\n\030GetPinnedFileIdsPRe" +
      "quest\022<\n\007options\030\001 \001(\0132+.alluxio.grpc.fi" +
      "le.GetPinnedFileIdsPOptions\"B\n\023GetUfsInf" +
      "oPResponse\022+\n\007ufsInfo\030\001 \001(\0132\032.alluxio.gr" +
      "pc.file.UfsInfo\"\024\n\022GetUfsInfoPOptions\"]\n" +
      "\022GetUfsInfoPRequest\022\017\n\007mountId\030\001 \001(\003\0226\n\007" +
      "options\030\002 \001(\0132%.alluxio.grpc.file.GetUfs" +
      "InfoPOptions*h\n\nWritePType\022\016\n\nMUST_CACHE" +
      "\020\001\022\r\n\tTRY_CACHE\020\002\022\021\n\rCACHE_THROUGH\020\003\022\013\n\007" +
      "THROUGH\020\004\022\021\n\rASYNC_THROUGH\020\005\022\010\n\004NONE\020\006*7" +
      "\n\tReadPType\022\014\n\010NO_CACHE\020\001\022\t\n\005CACHE\020\002\022\021\n\r" +
      "CACHE_PROMOTE\020\003*4\n\021LoadMetadataPType\022\t\n\005" +
      "NEVER\020\000\022\010\n\004ONCE\020\001\022\n\n\006ALWAYS\020\002*N\n\017SyncPoi" +
      "ntStatus\022\030\n\024Not_Initially_Synced\020\000\022\013\n\007Sy" +
      "ncing\020\001\022\024\n\020Initially_Synced\020\002*_\n\rPAclEnt" +
      "ryType\022\t\n\005Owner\020\000\022\r\n\tNamedUser\020\001\022\017\n\013Owni" +
      "ngGroup\020\002\022\016\n\nNamedGroup\020\003\022\010\n\004Mask\020\004\022\t\n\005O" +
      "ther\020\005*.\n\nPAclAction\022\010\n\004Read\020\000\022\t\n\005Write\020" +
      "\001\022\013\n\007Execute\020\002*W\n\014SetAclAction\022\013\n\007REPLAC" +
      "E\020\000\022\n\n\006MODIFY\020\001\022\n\n\006REMOVE\020\002\022\016\n\nREMOVE_AL" +
      "L\020\003\022\022\n\016REMOVE_DEFAULT\020\004*8\n\010UfsPMode\022\r\n\tN" +
      "O_ACCESS\020\001\022\r\n\tREAD_ONLY\020\002\022\016\n\nREAD_WRITE\020" +
      "\0032\216\022\n\035FileSystemMasterClientService\022m\n\020C" +
      "heckConsistency\022+.alluxio.grpc.file.Chec" +
      "kConsistencyPRequest\032,.alluxio.grpc.file" +
      ".CheckConsistencyPResponse\022a\n\014CompleteFi" +
      "le\022\'.alluxio.grpc.file.CompleteFilePRequ" +
      "est\032(.alluxio.grpc.file.CompleteFilePRes" +
      "ponse\022j\n\017CreateDirectory\022*.alluxio.grpc." +
      "file.CreateDirectoryPRequest\032+.alluxio.g" +
      "rpc.file.CreateDirectoryPResponse\022[\n\nCre" +
      "ateFile\022%.alluxio.grpc.file.CreateFilePR" +
      "equest\032&.alluxio.grpc.file.CreateFilePRe" +
      "sponse\022I\n\004Free\022\037.alluxio.grpc.file.FreeP" +
      "Request\032 .alluxio.grpc.file.FreePRespons" +
      "e\022d\n\rGetMountTable\022(.alluxio.grpc.file.G" +
      "etMountTablePRequest\032).alluxio.grpc.file" +
      ".GetMountTablePResponse\022j\n\017GetSyncPathLi" +
      "st\022*.alluxio.grpc.file.GetSyncPathListPR" +
      "equest\032+.alluxio.grpc.file.GetSyncPathLi" +
      "stPResponse\022y\n\024GetNewBlockIdForFile\022/.al" +
      "luxio.grpc.file.GetNewBlockIdForFilePReq" +
      "uest\0320.alluxio.grpc.file.GetNewBlockIdFo" +
      "rFilePResponse\022X\n\tGetStatus\022$.alluxio.gr" +
      "pc.file.GetStatusPRequest\032%.alluxio.grpc" +
      ".file.GetStatusPResponse\022[\n\nListStatus\022%" +
      ".alluxio.grpc.file.ListStatusPRequest\032&." +
      "alluxio.grpc.file.ListStatusPResponse\022L\n" +
      "\005Mount\022 .alluxio.grpc.file.MountPRequest" +
      "\032!.alluxio.grpc.file.MountPResponse\022O\n\006R" +
      "emove\022!.alluxio.grpc.file.DeletePRequest" +
      "\032\".alluxio.grpc.file.DeletePResponse\022O\n\006" +
      "Rename\022!.alluxio.grpc.file.RenamePReques" +
      "t\032\".alluxio.grpc.file.RenamePResponse\022\205\001" +
      "\n\030ScheduleAsyncPersistence\0223.alluxio.grp" +
      "c.file.ScheduleAsyncPersistencePRequest\032" +
      "4.alluxio.grpc.file.ScheduleAsyncPersist" +
      "encePResponse\022O\n\006SetAcl\022!.alluxio.grpc.f" +
      "ile.SetAclPRequest\032\".alluxio.grpc.file.S" +
      "etAclPResponse\022a\n\014SetAttribute\022\'.alluxio" +
      ".grpc.file.SetAttributePRequest\032(.alluxi" +
      "o.grpc.file.SetAttributePResponse\022X\n\tSta" +
      "rtSync\022$.alluxio.grpc.file.StartSyncPReq" +
      "uest\032%.alluxio.grpc.file.StartSyncPRespo" +
      "nse\022U\n\010StopSync\022#.alluxio.grpc.file.Stop" +
      "SyncPRequest\032$.alluxio.grpc.file.StopSyn" +
      "cPResponse\022R\n\007Unmount\022\".alluxio.grpc.fil" +
      "e.UnmountPRequest\032#.alluxio.grpc.file.Un" +
      "mountPResponse\022d\n\rUpdateUfsMode\022(.alluxi" +
      "o.grpc.file.UpdateUfsModePRequest\032).allu" +
      "xio.grpc.file.UpdateUfsModePResponse\022s\n\022" +
      "GetDelegationToken\022-.alluxio.grpc.file.G" +
      "etDelegationTokenPRequest\032..alluxio.grpc" +
      ".file.GetDelegationTokenPResponse\022y\n\024Ren" +
      "ewDelegationToken\022/.alluxio.grpc.file.Re" +
      "newDelegationTokenPRequest\0320.alluxio.grp" +
      "c.file.RenewDelegationTokenPResponse\022|\n\025" +
      "CancelDelegationToken\0220.alluxio.grpc.fil" +
      "e.CancelDelegationTokenPRequest\0321.alluxi" +
      "o.grpc.file.CancelDelegationTokenPRespon" +
      "se2\303\003\n\035FileSystemMasterWorkerService\022v\n\023" +
      "FileSystemHeartbeat\022..alluxio.grpc.file." +
      "FileSystemHeartbeatPRequest\032/.alluxio.gr" +
      "pc.file.FileSystemHeartbeatPResponse\022^\n\013" +
      "GetFileInfo\022&.alluxio.grpc.file.GetFileI" +
      "nfoPRequest\032\'.alluxio.grpc.file.GetFileI" +
      "nfoPResponse\022m\n\020GetPinnedFileIds\022+.allux" +
      "io.grpc.file.GetPinnedFileIdsPRequest\032,." +
      "alluxio.grpc.file.GetPinnedFileIdsPRespo" +
      "nse\022[\n\nGetUfsInfo\022%.alluxio.grpc.file.Ge" +
      "tUfsInfoPRequest\032&.alluxio.grpc.file.Get" +
      "UfsInfoPResponse2\331\001\n\032FileSystemMasterJob" +
      "Service\022^\n\013GetFileInfo\022&.alluxio.grpc.fi" +
      "le.GetFileInfoPRequest\032\'.alluxio.grpc.fi" +
      "le.GetFileInfoPResponse\022[\n\nGetUfsInfo\022%." +
      "alluxio.grpc.file.GetUfsInfoPRequest\032&.a" +
      "lluxio.grpc.file.GetUfsInfoPResponseB\'\n\014" +
      "alluxio.grpcB\025FileSystemMasterProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          alluxio.grpc.CommonProto.getDescriptor(),
          alluxio.grpc.FsCommonProto.getDescriptor(),
          alluxio.proto.security.CapabilityProto.getDescriptor(),
        }, assigner);
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemMasterCommonPOptions_descriptor,
        new java.lang.String[] { "SyncIntervalMs", "Ttl", "TtlAction", });
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alluxio_grpc_file_CheckConsistencyPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPResponse_descriptor,
        new java.lang.String[] { "InconsistentPaths", });
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alluxio_grpc_file_CheckConsistencyPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alluxio_grpc_file_CheckConsistencyPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CheckConsistencyPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_alluxio_grpc_file_CompleteFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_alluxio_grpc_file_CompleteFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePOptions_descriptor,
        new java.lang.String[] { "UfsLength", "CommonOptions", });
    internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_alluxio_grpc_file_CompleteFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CompleteFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_alluxio_grpc_file_OpenFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_OpenFilePOptions_descriptor,
        new java.lang.String[] { "ReadType", "MaxUfsReadConcurrency", "FileReadLocationPolicy", "HashingNumberOfShards", "CommonOptions", "SkipTransformation", });
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_alluxio_grpc_file_CreateDirectoryPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_alluxio_grpc_file_CreateDirectoryPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPOptions_descriptor,
        new java.lang.String[] { "Recursive", "AllowExists", "Mode", "WriteType", "CommonOptions", });
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_alluxio_grpc_file_CreateDirectoryPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateDirectoryPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_alluxio_grpc_file_CreateFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_alluxio_grpc_file_CreateFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePOptions_descriptor,
        new java.lang.String[] { "BlockSizeBytes", "Recursive", "Mode", "ReplicationMax", "ReplicationMin", "ReplicationDurable", "FileWriteLocationPolicy", "WriteTier", "WriteType", "CommonOptions", });
    internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_alluxio_grpc_file_CreateFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CreateFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_DeletePResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_alluxio_grpc_file_DeletePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_DeletePOptions_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_alluxio_grpc_file_DeletePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePOptions_descriptor,
        new java.lang.String[] { "Recursive", "AlluxioOnly", "Unchecked", "CommonOptions", });
    internal_static_alluxio_grpc_file_DeletePRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_alluxio_grpc_file_DeletePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DeletePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_FreePResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_alluxio_grpc_file_FreePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_FreePOptions_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_alluxio_grpc_file_FreePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePOptions_descriptor,
        new java.lang.String[] { "Recursive", "Forced", "CommonOptions", });
    internal_static_alluxio_grpc_file_FreePRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_alluxio_grpc_file_FreePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FreePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetNewBlockIdForFilePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_alluxio_grpc_file_GetStatusPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPResponse_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_alluxio_grpc_file_GetStatusPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPOptions_descriptor,
        new java.lang.String[] { "LoadMetadataType", "CommonOptions", "AccessMode", });
    internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_alluxio_grpc_file_GetStatusPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetStatusPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_DelegationTokenIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_alluxio_grpc_file_DelegationTokenIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DelegationTokenIdentifier_descriptor,
        new java.lang.String[] { "Owner", "Renewer", "RealUser", "IssueDate", "MaxDate", "SequenceNumber", "MasterKeyId", });
    internal_static_alluxio_grpc_file_DelegationToken_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_alluxio_grpc_file_DelegationToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_DelegationToken_descriptor,
        new java.lang.String[] { "Identifier", "Password", });
    internal_static_alluxio_grpc_file_GetDelegationTokenPResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_alluxio_grpc_file_GetDelegationTokenPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetDelegationTokenPResponse_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_alluxio_grpc_file_GetDelegationTokenPRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_alluxio_grpc_file_GetDelegationTokenPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetDelegationTokenPRequest_descriptor,
        new java.lang.String[] { "Renewer", });
    internal_static_alluxio_grpc_file_RenewDelegationTokenPResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_alluxio_grpc_file_RenewDelegationTokenPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenewDelegationTokenPResponse_descriptor,
        new java.lang.String[] { "ExpirationTimeMs", });
    internal_static_alluxio_grpc_file_RenewDelegationTokenPRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_alluxio_grpc_file_RenewDelegationTokenPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenewDelegationTokenPRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_alluxio_grpc_file_CancelDelegationTokenPResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_alluxio_grpc_file_CancelDelegationTokenPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CancelDelegationTokenPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_CancelDelegationTokenPRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_alluxio_grpc_file_CancelDelegationTokenPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_CancelDelegationTokenPRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_alluxio_grpc_file_ExistsPOptions_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_alluxio_grpc_file_ExistsPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ExistsPOptions_descriptor,
        new java.lang.String[] { "LoadMetadataType", "CommonOptions", });
    internal_static_alluxio_grpc_file_SyncPointInfo_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_alluxio_grpc_file_SyncPointInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SyncPointInfo_descriptor,
        new java.lang.String[] { "SyncPointUri", "SyncStatus", });
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_alluxio_grpc_file_GetSyncPathListPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetSyncPathListPResponse_descriptor,
        new java.lang.String[] { "SyncPaths", });
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_alluxio_grpc_file_GetSyncPathListPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetSyncPathListPRequest_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_alluxio_grpc_file_ListStatusPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPResponse_descriptor,
        new java.lang.String[] { "FileInfos", });
    internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_alluxio_grpc_file_ListStatusPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPOptions_descriptor,
        new java.lang.String[] { "LoadDirectChildren", "LoadMetadataType", "CommonOptions", "Recursive", });
    internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_alluxio_grpc_file_ListStatusPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ListStatusPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_alluxio_grpc_file_LoadMetadataPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_alluxio_grpc_file_LoadMetadataPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPOptions_descriptor,
        new java.lang.String[] { "Recursive", "CreateAncestors", "LoadDescendantType", "CommonOptions", });
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_alluxio_grpc_file_LoadMetadataPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_LoadMetadataPRequest_descriptor,
        new java.lang.String[] { "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_PAclEntry_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_alluxio_grpc_file_PAclEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PAclEntry_descriptor,
        new java.lang.String[] { "Type", "Subject", "Actions", "IsDefault", });
    internal_static_alluxio_grpc_file_PAcl_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_alluxio_grpc_file_PAcl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PAcl_descriptor,
        new java.lang.String[] { "Owner", "OwningGroup", "Entries", "Mode", "IsDefault", "IsDefaultEmpty", });
    internal_static_alluxio_grpc_file_FileBlockInfo_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_alluxio_grpc_file_FileBlockInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileBlockInfo_descriptor,
        new java.lang.String[] { "BlockInfo", "Offset", "UfsLocations", "UfsStringLocations", });
    internal_static_alluxio_grpc_file_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_alluxio_grpc_file_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileInfo_descriptor,
        new java.lang.String[] { "FileId", "Name", "Path", "UfsPath", "Length", "BlockSizeBytes", "CreationTimeMs", "Completed", "Folder", "Pinned", "Cacheable", "Persisted", "BlockIds", "LastModificationTimeMs", "Ttl", "Owner", "Group", "Mode", "PersistenceState", "MountPoint", "FileBlockInfos", "TtlAction", "MountId", "InAlluxioPercentage", "InMemoryPercentage", "UfsFingerprint", "Acl", "DefaultAcl", "ReplicationMax", "ReplicationMin", "Capability", "Encrypted", });
    internal_static_alluxio_grpc_file_MountPResponse_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_alluxio_grpc_file_MountPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_MountPOptions_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_alluxio_grpc_file_MountPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPOptions_descriptor,
        new java.lang.String[] { "ReadOnly", "Properties", "Shared", "CommonOptions", });
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor =
      internal_static_alluxio_grpc_file_MountPOptions_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPOptions_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_MountPRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_alluxio_grpc_file_MountPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPRequest_descriptor,
        new java.lang.String[] { "AlluxioPath", "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_alluxio_grpc_file_GetMountTablePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor,
        new java.lang.String[] { "MountPoints", });
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor =
      internal_static_alluxio_grpc_file_GetMountTablePResponse_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePResponse_MountPointsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_alluxio_grpc_file_GetMountTablePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetMountTablePRequest_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_MountPointInfo_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_alluxio_grpc_file_MountPointInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPointInfo_descriptor,
        new java.lang.String[] { "UfsUri", "UfsType", "UfsCapacityBytes", "UfsUsedBytes", "ReadOnly", "Properties", "Shared", });
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor =
      internal_static_alluxio_grpc_file_MountPointInfo_descriptor.getNestedTypes().get(0);
    internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_MountPointInfo_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_alluxio_grpc_file_FileSystemCommandOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemCommandOptions_descriptor,
        new java.lang.String[] { "PersistOptions", });
    internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_alluxio_grpc_file_PersistCommandOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PersistCommandOptions_descriptor,
        new java.lang.String[] { "PersistFiles", });
    internal_static_alluxio_grpc_file_PersistFile_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_alluxio_grpc_file_PersistFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_PersistFile_descriptor,
        new java.lang.String[] { "FileId", "BlockIds", });
    internal_static_alluxio_grpc_file_FileSystemCommand_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_alluxio_grpc_file_FileSystemCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemCommand_descriptor,
        new java.lang.String[] { "CommandType", "CommandOptions", });
    internal_static_alluxio_grpc_file_RenamePResponse_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_alluxio_grpc_file_RenamePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_RenamePOptions_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_alluxio_grpc_file_RenamePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_RenamePRequest_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_alluxio_grpc_file_RenamePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_RenamePRequest_descriptor,
        new java.lang.String[] { "Path", "DstPath", "Options", });
    internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_alluxio_grpc_file_SetAttributePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_alluxio_grpc_file_SetAttributePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePOptions_descriptor,
        new java.lang.String[] { "Pinned", "Ttl", "TtlAction", "Persisted", "Owner", "Group", "Mode", "Recursive", "ReplicationMax", "ReplicationMin", "CommonOptions", });
    internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_alluxio_grpc_file_SetAttributePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAttributePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_SetAclPResponse_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_alluxio_grpc_file_SetAclPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_SetAclPOptions_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_alluxio_grpc_file_SetAclPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", "Recursive", });
    internal_static_alluxio_grpc_file_SetAclPRequest_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_alluxio_grpc_file_SetAclPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_SetAclPRequest_descriptor,
        new java.lang.String[] { "Path", "Action", "Entries", "Options", });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_ScheduleAsyncPersistencePRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_alluxio_grpc_file_StartSyncPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_alluxio_grpc_file_StartSyncPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_alluxio_grpc_file_StartSyncPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StartSyncPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_alluxio_grpc_file_StopSyncPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_alluxio_grpc_file_StopSyncPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_alluxio_grpc_file_StopSyncPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_StopSyncPRequest_descriptor,
        new java.lang.String[] { "Path", "Options", });
    internal_static_alluxio_grpc_file_UnmountPResponse_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_alluxio_grpc_file_UnmountPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_UnmountPOptions_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_alluxio_grpc_file_UnmountPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPOptions_descriptor,
        new java.lang.String[] { "CommonOptions", });
    internal_static_alluxio_grpc_file_UnmountPRequest_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_alluxio_grpc_file_UnmountPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UnmountPRequest_descriptor,
        new java.lang.String[] { "AlluxioPath", "Options", });
    internal_static_alluxio_grpc_file_UfsInfo_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_alluxio_grpc_file_UfsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UfsInfo_descriptor,
        new java.lang.String[] { "Uri", "Properties", });
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_alluxio_grpc_file_UpdateUfsModePResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_alluxio_grpc_file_UpdateUfsModePOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePOptions_descriptor,
        new java.lang.String[] { "UfsMode", });
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_alluxio_grpc_file_UpdateUfsModePRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_UpdateUfsModePRequest_descriptor,
        new java.lang.String[] { "UfsPath", "Options", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPResponse_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPOptions_descriptor,
        new java.lang.String[] { "PersistedFileFingerprints", });
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_FileSystemHeartbeatPRequest_descriptor,
        new java.lang.String[] { "WorkerId", "PersistedFiles", "Options", });
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_alluxio_grpc_file_GetFileInfoPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPResponse_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor =
      getDescriptor().getMessageTypes().get(87);
    internal_static_alluxio_grpc_file_GetFileInfoPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor =
      getDescriptor().getMessageTypes().get(88);
    internal_static_alluxio_grpc_file_GetFileInfoPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetFileInfoPRequest_descriptor,
        new java.lang.String[] { "FileId", "Options", });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor =
      getDescriptor().getMessageTypes().get(89);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPResponse_descriptor,
        new java.lang.String[] { "PinnedFileIds", });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor =
      getDescriptor().getMessageTypes().get(90);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor =
      getDescriptor().getMessageTypes().get(91);
    internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetPinnedFileIdsPRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor =
      getDescriptor().getMessageTypes().get(92);
    internal_static_alluxio_grpc_file_GetUfsInfoPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPResponse_descriptor,
        new java.lang.String[] { "UfsInfo", });
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor =
      getDescriptor().getMessageTypes().get(93);
    internal_static_alluxio_grpc_file_GetUfsInfoPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor =
      getDescriptor().getMessageTypes().get(94);
    internal_static_alluxio_grpc_file_GetUfsInfoPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_file_GetUfsInfoPRequest_descriptor,
        new java.lang.String[] { "MountId", "Options", });
    alluxio.grpc.CommonProto.getDescriptor();
    alluxio.grpc.FsCommonProto.getDescriptor();
    alluxio.proto.security.CapabilityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
