// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/policy_master.proto

package alluxio.grpc;

public final class PolicyMasterProto {
  private PolicyMasterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_PolicyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_PolicyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_ListPolicyPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_ListPolicyPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_ListPolicyPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_ListPolicyPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_ListPolicyPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_ListPolicyPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_AddPolicyPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_AddPolicyPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_AddPolicyPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_AddPolicyPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_AddPolicyPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_AddPolicyPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_RemovePolicyPResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_RemovePolicyPResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_RemovePolicyPOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_RemovePolicyPOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_grpc_policy_RemovePolicyPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_grpc_policy_RemovePolicyPRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030grpc/policy_master.proto\022\023alluxio.grpc" +
      ".policy\"z\n\nPolicyInfo\022\n\n\002id\030\001 \001(\003\022\014\n\004nam" +
      "e\030\002 \001(\t\022\014\n\004path\030\003 \001(\t\022\022\n\ncreated_at\030\004 \001(" +
      "\003\022\r\n\005scope\030\005 \001(\t\022\021\n\tcondition\030\006 \001(\t\022\016\n\006a" +
      "ction\030\007 \001(\t\"F\n\023ListPolicyPResponse\022/\n\006po" +
      "licy\030\001 \003(\0132\037.alluxio.grpc.policy.PolicyI" +
      "nfo\"\024\n\022ListPolicyPOptions\"N\n\022ListPolicyP" +
      "Request\0228\n\007options\030\001 \001(\0132\'.alluxio.grpc." +
      "policy.ListPolicyPOptions\"\024\n\022AddPolicyPR" +
      "esponse\"\023\n\021AddPolicyPOptions\"u\n\021AddPolic" +
      "yPRequest\022\023\n\013alluxioPath\030\001 \001(\t\022\022\n\ndefini" +
      "tion\030\002 \001(\t\0227\n\007options\030\003 \001(\0132&.alluxio.gr" +
      "pc.policy.AddPolicyPOptions\"\027\n\025RemovePol" +
      "icyPResponse\"\026\n\024RemovePolicyPOptions\"f\n\024" +
      "RemovePolicyPRequest\022\022\n\npolicyName\030\001 \001(\t" +
      "\022:\n\007options\030\002 \001(\0132).alluxio.grpc.policy." +
      "RemovePolicyPOptions2\301\002\n\031PolicyMasterCli" +
      "entService\022_\n\nListPolicy\022\'.alluxio.grpc." +
      "policy.ListPolicyPRequest\032(.alluxio.grpc" +
      ".policy.ListPolicyPResponse\022\\\n\tAddPolicy" +
      "\022&.alluxio.grpc.policy.AddPolicyPRequest" +
      "\032\'.alluxio.grpc.policy.AddPolicyPRespons" +
      "e\022e\n\014RemovePolicy\022).alluxio.grpc.policy." +
      "RemovePolicyPRequest\032*.alluxio.grpc.poli" +
      "cy.RemovePolicyPResponseB#\n\014alluxio.grpc" +
      "B\021PolicyMasterProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alluxio_grpc_policy_PolicyInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alluxio_grpc_policy_PolicyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_PolicyInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Path", "CreatedAt", "Scope", "Condition", "Action", });
    internal_static_alluxio_grpc_policy_ListPolicyPResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alluxio_grpc_policy_ListPolicyPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_ListPolicyPResponse_descriptor,
        new java.lang.String[] { "Policy", });
    internal_static_alluxio_grpc_policy_ListPolicyPOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_alluxio_grpc_policy_ListPolicyPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_ListPolicyPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_policy_ListPolicyPRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_alluxio_grpc_policy_ListPolicyPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_ListPolicyPRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_alluxio_grpc_policy_AddPolicyPResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_alluxio_grpc_policy_AddPolicyPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_AddPolicyPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_policy_AddPolicyPOptions_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_alluxio_grpc_policy_AddPolicyPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_AddPolicyPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_policy_AddPolicyPRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_alluxio_grpc_policy_AddPolicyPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_AddPolicyPRequest_descriptor,
        new java.lang.String[] { "AlluxioPath", "Definition", "Options", });
    internal_static_alluxio_grpc_policy_RemovePolicyPResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_alluxio_grpc_policy_RemovePolicyPResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_RemovePolicyPResponse_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_policy_RemovePolicyPOptions_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_alluxio_grpc_policy_RemovePolicyPOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_RemovePolicyPOptions_descriptor,
        new java.lang.String[] { });
    internal_static_alluxio_grpc_policy_RemovePolicyPRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_alluxio_grpc_policy_RemovePolicyPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_grpc_policy_RemovePolicyPRequest_descriptor,
        new java.lang.String[] { "PolicyName", "Options", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
