// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/secure_rpc_server.proto

package alluxio.grpc;

public interface WriteSecretKeyPResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.securerpc.WriteSecretKeyPResponse)
    com.google.protobuf.MessageOrBuilder {
}
