#!/usr/bin/env bash
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# Builds the Alluxio native library.

set -e

OPENSSL_ROOT_DIR=$1
CWD=$(cd "$( dirname "$0" )"; pwd)
CMAKE_DIR=${CWD}/cmake

rm -rf ${CMAKE_DIR} && mkdir -p ${CMAKE_DIR}
pushd ${CMAKE_DIR}
cmake -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} ..
make
popd
