// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/security/capability_proto.proto

package alluxio.proto.security;

public final class CapabilityProto {
  private CapabilityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alluxio.proto.security.Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The walltime at which this content expires.
     * </pre>
     *
     * <code>optional int64 expiration_time_ms = 1;</code>
     */
    boolean hasExpirationTimeMs();
    /**
     * <pre>
     * The walltime at which this content expires.
     * </pre>
     *
     * <code>optional int64 expiration_time_ms = 1;</code>
     */
    long getExpirationTimeMs();

    /**
     * <pre>
     * The file ID.
     * </pre>
     *
     * <code>optional int64 file_id = 2;</code>
     */
    boolean hasFileId();
    /**
     * <pre>
     * The file ID.
     * </pre>
     *
     * <code>optional int64 file_id = 2;</code>
     */
    long getFileId();

    /**
     * <pre>
     * The access mode granted to the user.
     * </pre>
     *
     * <code>optional int32 access_mode = 3;</code>
     */
    boolean hasAccessMode();
    /**
     * <pre>
     * The access mode granted to the user.
     * </pre>
     *
     * <code>optional int32 access_mode = 3;</code>
     */
    int getAccessMode();

    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    boolean hasUser();
    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    java.lang.String getUser();
    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <pre>
     * The key id.
     * </pre>
     *
     * <code>optional int64 key_id = 5;</code>
     */
    boolean hasKeyId();
    /**
     * <pre>
     * The key id.
     * </pre>
     *
     * <code>optional int64 key_id = 5;</code>
     */
    long getKeyId();
  }
  /**
   * <pre>
   * The capability content has the information fields representing a short-lived user access
   * capability to a file.
   * </pre>
   *
   * Protobuf type {@code alluxio.proto.security.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:alluxio.proto.security.Content)
      ContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() {
      expirationTimeMs_ = 0L;
      fileId_ = 0L;
      accessMode_ = 0;
      user_ = "";
      keyId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              expirationTimeMs_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fileId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              accessMode_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              user_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              keyId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Content_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.proto.security.CapabilityProto.Content.class, alluxio.proto.security.CapabilityProto.Content.Builder.class);
    }

    private int bitField0_;
    public static final int EXPIRATION_TIME_MS_FIELD_NUMBER = 1;
    private long expirationTimeMs_;
    /**
     * <pre>
     * The walltime at which this content expires.
     * </pre>
     *
     * <code>optional int64 expiration_time_ms = 1;</code>
     */
    public boolean hasExpirationTimeMs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The walltime at which this content expires.
     * </pre>
     *
     * <code>optional int64 expiration_time_ms = 1;</code>
     */
    public long getExpirationTimeMs() {
      return expirationTimeMs_;
    }

    public static final int FILE_ID_FIELD_NUMBER = 2;
    private long fileId_;
    /**
     * <pre>
     * The file ID.
     * </pre>
     *
     * <code>optional int64 file_id = 2;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * The file ID.
     * </pre>
     *
     * <code>optional int64 file_id = 2;</code>
     */
    public long getFileId() {
      return fileId_;
    }

    public static final int ACCESS_MODE_FIELD_NUMBER = 3;
    private int accessMode_;
    /**
     * <pre>
     * The access mode granted to the user.
     * </pre>
     *
     * <code>optional int32 access_mode = 3;</code>
     */
    public boolean hasAccessMode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * The access mode granted to the user.
     * </pre>
     *
     * <code>optional int32 access_mode = 3;</code>
     */
    public int getAccessMode() {
      return accessMode_;
    }

    public static final int USER_FIELD_NUMBER = 4;
    private volatile java.lang.Object user_;
    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * The user name.
     * </pre>
     *
     * <code>optional string user = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_ID_FIELD_NUMBER = 5;
    private long keyId_;
    /**
     * <pre>
     * The key id.
     * </pre>
     *
     * <code>optional int64 key_id = 5;</code>
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * The key id.
     * </pre>
     *
     * <code>optional int64 key_id = 5;</code>
     */
    public long getKeyId() {
      return keyId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, expirationTimeMs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fileId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, accessMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, user_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, keyId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, expirationTimeMs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fileId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, accessMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, user_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, keyId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof alluxio.proto.security.CapabilityProto.Content)) {
        return super.equals(obj);
      }
      alluxio.proto.security.CapabilityProto.Content other = (alluxio.proto.security.CapabilityProto.Content) obj;

      boolean result = true;
      result = result && (hasExpirationTimeMs() == other.hasExpirationTimeMs());
      if (hasExpirationTimeMs()) {
        result = result && (getExpirationTimeMs()
            == other.getExpirationTimeMs());
      }
      result = result && (hasFileId() == other.hasFileId());
      if (hasFileId()) {
        result = result && (getFileId()
            == other.getFileId());
      }
      result = result && (hasAccessMode() == other.hasAccessMode());
      if (hasAccessMode()) {
        result = result && (getAccessMode()
            == other.getAccessMode());
      }
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasKeyId() == other.hasKeyId());
      if (hasKeyId()) {
        result = result && (getKeyId()
            == other.getKeyId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasExpirationTimeMs()) {
        hash = (37 * hash) + EXPIRATION_TIME_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExpirationTimeMs());
      }
      if (hasFileId()) {
        hash = (37 * hash) + FILE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFileId());
      }
      if (hasAccessMode()) {
        hash = (37 * hash) + ACCESS_MODE_FIELD_NUMBER;
        hash = (53 * hash) + getAccessMode();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasKeyId()) {
        hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getKeyId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(alluxio.proto.security.CapabilityProto.Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The capability content has the information fields representing a short-lived user access
     * capability to a file.
     * </pre>
     *
     * Protobuf type {@code alluxio.proto.security.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alluxio.proto.security.Content)
        alluxio.proto.security.CapabilityProto.ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Content_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                alluxio.proto.security.CapabilityProto.Content.class, alluxio.proto.security.CapabilityProto.Content.Builder.class);
      }

      // Construct using alluxio.proto.security.CapabilityProto.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        expirationTimeMs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        accessMode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        keyId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Content_descriptor;
      }

      public alluxio.proto.security.CapabilityProto.Content getDefaultInstanceForType() {
        return alluxio.proto.security.CapabilityProto.Content.getDefaultInstance();
      }

      public alluxio.proto.security.CapabilityProto.Content build() {
        alluxio.proto.security.CapabilityProto.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public alluxio.proto.security.CapabilityProto.Content buildPartial() {
        alluxio.proto.security.CapabilityProto.Content result = new alluxio.proto.security.CapabilityProto.Content(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.expirationTimeMs_ = expirationTimeMs_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.accessMode_ = accessMode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.keyId_ = keyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alluxio.proto.security.CapabilityProto.Content) {
          return mergeFrom((alluxio.proto.security.CapabilityProto.Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(alluxio.proto.security.CapabilityProto.Content other) {
        if (other == alluxio.proto.security.CapabilityProto.Content.getDefaultInstance()) return this;
        if (other.hasExpirationTimeMs()) {
          setExpirationTimeMs(other.getExpirationTimeMs());
        }
        if (other.hasFileId()) {
          setFileId(other.getFileId());
        }
        if (other.hasAccessMode()) {
          setAccessMode(other.getAccessMode());
        }
        if (other.hasUser()) {
          bitField0_ |= 0x00000008;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasKeyId()) {
          setKeyId(other.getKeyId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        alluxio.proto.security.CapabilityProto.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (alluxio.proto.security.CapabilityProto.Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long expirationTimeMs_ ;
      /**
       * <pre>
       * The walltime at which this content expires.
       * </pre>
       *
       * <code>optional int64 expiration_time_ms = 1;</code>
       */
      public boolean hasExpirationTimeMs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * The walltime at which this content expires.
       * </pre>
       *
       * <code>optional int64 expiration_time_ms = 1;</code>
       */
      public long getExpirationTimeMs() {
        return expirationTimeMs_;
      }
      /**
       * <pre>
       * The walltime at which this content expires.
       * </pre>
       *
       * <code>optional int64 expiration_time_ms = 1;</code>
       */
      public Builder setExpirationTimeMs(long value) {
        bitField0_ |= 0x00000001;
        expirationTimeMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The walltime at which this content expires.
       * </pre>
       *
       * <code>optional int64 expiration_time_ms = 1;</code>
       */
      public Builder clearExpirationTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        expirationTimeMs_ = 0L;
        onChanged();
        return this;
      }

      private long fileId_ ;
      /**
       * <pre>
       * The file ID.
       * </pre>
       *
       * <code>optional int64 file_id = 2;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * The file ID.
       * </pre>
       *
       * <code>optional int64 file_id = 2;</code>
       */
      public long getFileId() {
        return fileId_;
      }
      /**
       * <pre>
       * The file ID.
       * </pre>
       *
       * <code>optional int64 file_id = 2;</code>
       */
      public Builder setFileId(long value) {
        bitField0_ |= 0x00000002;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The file ID.
       * </pre>
       *
       * <code>optional int64 file_id = 2;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileId_ = 0L;
        onChanged();
        return this;
      }

      private int accessMode_ ;
      /**
       * <pre>
       * The access mode granted to the user.
       * </pre>
       *
       * <code>optional int32 access_mode = 3;</code>
       */
      public boolean hasAccessMode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * The access mode granted to the user.
       * </pre>
       *
       * <code>optional int32 access_mode = 3;</code>
       */
      public int getAccessMode() {
        return accessMode_;
      }
      /**
       * <pre>
       * The access mode granted to the user.
       * </pre>
       *
       * <code>optional int32 access_mode = 3;</code>
       */
      public Builder setAccessMode(int value) {
        bitField0_ |= 0x00000004;
        accessMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The access mode granted to the user.
       * </pre>
       *
       * <code>optional int32 access_mode = 3;</code>
       */
      public Builder clearAccessMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        accessMode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            user_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000008);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The user name.
       * </pre>
       *
       * <code>optional string user = 4;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        user_ = value;
        onChanged();
        return this;
      }

      private long keyId_ ;
      /**
       * <pre>
       * The key id.
       * </pre>
       *
       * <code>optional int64 key_id = 5;</code>
       */
      public boolean hasKeyId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * The key id.
       * </pre>
       *
       * <code>optional int64 key_id = 5;</code>
       */
      public long getKeyId() {
        return keyId_;
      }
      /**
       * <pre>
       * The key id.
       * </pre>
       *
       * <code>optional int64 key_id = 5;</code>
       */
      public Builder setKeyId(long value) {
        bitField0_ |= 0x00000010;
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key id.
       * </pre>
       *
       * <code>optional int64 key_id = 5;</code>
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        keyId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:alluxio.proto.security.Content)
    }

    // @@protoc_insertion_point(class_scope:alluxio.proto.security.Content)
    private static final alluxio.proto.security.CapabilityProto.Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new alluxio.proto.security.CapabilityProto.Content();
    }

    public static alluxio.proto.security.CapabilityProto.Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    public alluxio.proto.security.CapabilityProto.Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CapabilityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:alluxio.proto.security.Capability)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The serialized capability content.
     * </pre>
     *
     * <code>optional bytes content = 1;</code>
     */
    boolean hasContent();
    /**
     * <pre>
     * The serialized capability content.
     * </pre>
     *
     * <code>optional bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     * The authenticator.
     * </pre>
     *
     * <code>optional bytes authenticator = 2;</code>
     */
    boolean hasAuthenticator();
    /**
     * <pre>
     * The authenticator.
     * </pre>
     *
     * <code>optional bytes authenticator = 2;</code>
     */
    com.google.protobuf.ByteString getAuthenticator();

    /**
     * <pre>
     * The capability key ID.
     * </pre>
     *
     * <code>optional int64 key_id = 3;</code>
     */
    boolean hasKeyId();
    /**
     * <pre>
     * The capability key ID.
     * </pre>
     *
     * <code>optional int64 key_id = 3;</code>
     */
    long getKeyId();
  }
  /**
   * Protobuf type {@code alluxio.proto.security.Capability}
   */
  public  static final class Capability extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:alluxio.proto.security.Capability)
      CapabilityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Capability.newBuilder() to construct.
    private Capability(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Capability() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      authenticator_ = com.google.protobuf.ByteString.EMPTY;
      keyId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Capability(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              authenticator_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              keyId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Capability_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Capability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.proto.security.CapabilityProto.Capability.class, alluxio.proto.security.CapabilityProto.Capability.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     * The serialized capability content.
     * </pre>
     *
     * <code>optional bytes content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The serialized capability content.
     * </pre>
     *
     * <code>optional bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int AUTHENTICATOR_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString authenticator_;
    /**
     * <pre>
     * The authenticator.
     * </pre>
     *
     * <code>optional bytes authenticator = 2;</code>
     */
    public boolean hasAuthenticator() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * The authenticator.
     * </pre>
     *
     * <code>optional bytes authenticator = 2;</code>
     */
    public com.google.protobuf.ByteString getAuthenticator() {
      return authenticator_;
    }

    public static final int KEY_ID_FIELD_NUMBER = 3;
    private long keyId_;
    /**
     * <pre>
     * The capability key ID.
     * </pre>
     *
     * <code>optional int64 key_id = 3;</code>
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * The capability key ID.
     * </pre>
     *
     * <code>optional int64 key_id = 3;</code>
     */
    public long getKeyId() {
      return keyId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, content_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, authenticator_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, keyId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, authenticator_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, keyId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof alluxio.proto.security.CapabilityProto.Capability)) {
        return super.equals(obj);
      }
      alluxio.proto.security.CapabilityProto.Capability other = (alluxio.proto.security.CapabilityProto.Capability) obj;

      boolean result = true;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && (hasAuthenticator() == other.hasAuthenticator());
      if (hasAuthenticator()) {
        result = result && getAuthenticator()
            .equals(other.getAuthenticator());
      }
      result = result && (hasKeyId() == other.hasKeyId());
      if (hasKeyId()) {
        result = result && (getKeyId()
            == other.getKeyId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasAuthenticator()) {
        hash = (37 * hash) + AUTHENTICATOR_FIELD_NUMBER;
        hash = (53 * hash) + getAuthenticator().hashCode();
      }
      if (hasKeyId()) {
        hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getKeyId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static alluxio.proto.security.CapabilityProto.Capability parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(alluxio.proto.security.CapabilityProto.Capability prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code alluxio.proto.security.Capability}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:alluxio.proto.security.Capability)
        alluxio.proto.security.CapabilityProto.CapabilityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Capability_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Capability_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                alluxio.proto.security.CapabilityProto.Capability.class, alluxio.proto.security.CapabilityProto.Capability.Builder.class);
      }

      // Construct using alluxio.proto.security.CapabilityProto.Capability.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        authenticator_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        keyId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alluxio.proto.security.CapabilityProto.internal_static_alluxio_proto_security_Capability_descriptor;
      }

      public alluxio.proto.security.CapabilityProto.Capability getDefaultInstanceForType() {
        return alluxio.proto.security.CapabilityProto.Capability.getDefaultInstance();
      }

      public alluxio.proto.security.CapabilityProto.Capability build() {
        alluxio.proto.security.CapabilityProto.Capability result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public alluxio.proto.security.CapabilityProto.Capability buildPartial() {
        alluxio.proto.security.CapabilityProto.Capability result = new alluxio.proto.security.CapabilityProto.Capability(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.authenticator_ = authenticator_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.keyId_ = keyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alluxio.proto.security.CapabilityProto.Capability) {
          return mergeFrom((alluxio.proto.security.CapabilityProto.Capability)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(alluxio.proto.security.CapabilityProto.Capability other) {
        if (other == alluxio.proto.security.CapabilityProto.Capability.getDefaultInstance()) return this;
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasAuthenticator()) {
          setAuthenticator(other.getAuthenticator());
        }
        if (other.hasKeyId()) {
          setKeyId(other.getKeyId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        alluxio.proto.security.CapabilityProto.Capability parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (alluxio.proto.security.CapabilityProto.Capability) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The serialized capability content.
       * </pre>
       *
       * <code>optional bytes content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * The serialized capability content.
       * </pre>
       *
       * <code>optional bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       * The serialized capability content.
       * </pre>
       *
       * <code>optional bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The serialized capability content.
       * </pre>
       *
       * <code>optional bytes content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString authenticator_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The authenticator.
       * </pre>
       *
       * <code>optional bytes authenticator = 2;</code>
       */
      public boolean hasAuthenticator() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * The authenticator.
       * </pre>
       *
       * <code>optional bytes authenticator = 2;</code>
       */
      public com.google.protobuf.ByteString getAuthenticator() {
        return authenticator_;
      }
      /**
       * <pre>
       * The authenticator.
       * </pre>
       *
       * <code>optional bytes authenticator = 2;</code>
       */
      public Builder setAuthenticator(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        authenticator_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The authenticator.
       * </pre>
       *
       * <code>optional bytes authenticator = 2;</code>
       */
      public Builder clearAuthenticator() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authenticator_ = getDefaultInstance().getAuthenticator();
        onChanged();
        return this;
      }

      private long keyId_ ;
      /**
       * <pre>
       * The capability key ID.
       * </pre>
       *
       * <code>optional int64 key_id = 3;</code>
       */
      public boolean hasKeyId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * The capability key ID.
       * </pre>
       *
       * <code>optional int64 key_id = 3;</code>
       */
      public long getKeyId() {
        return keyId_;
      }
      /**
       * <pre>
       * The capability key ID.
       * </pre>
       *
       * <code>optional int64 key_id = 3;</code>
       */
      public Builder setKeyId(long value) {
        bitField0_ |= 0x00000004;
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The capability key ID.
       * </pre>
       *
       * <code>optional int64 key_id = 3;</code>
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        keyId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:alluxio.proto.security.Capability)
    }

    // @@protoc_insertion_point(class_scope:alluxio.proto.security.Capability)
    private static final alluxio.proto.security.CapabilityProto.Capability DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new alluxio.proto.security.CapabilityProto.Capability();
    }

    public static alluxio.proto.security.CapabilityProto.Capability getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Capability>
        PARSER = new com.google.protobuf.AbstractParser<Capability>() {
      public Capability parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Capability(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Capability> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Capability> getParserForType() {
      return PARSER;
    }

    public alluxio.proto.security.CapabilityProto.Capability getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_proto_security_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_proto_security_Content_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alluxio_proto_security_Capability_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alluxio_proto_security_Capability_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%proto/security/capability_proto.proto\022" +
      "\026alluxio.proto.security\"i\n\007Content\022\032\n\022ex" +
      "piration_time_ms\030\001 \001(\003\022\017\n\007file_id\030\002 \001(\003\022" +
      "\023\n\013access_mode\030\003 \001(\005\022\014\n\004user\030\004 \001(\t\022\016\n\006ke" +
      "y_id\030\005 \001(\003\"D\n\nCapability\022\017\n\007content\030\001 \001(" +
      "\014\022\025\n\rauthenticator\030\002 \001(\014\022\016\n\006key_id\030\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alluxio_proto_security_Content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alluxio_proto_security_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_proto_security_Content_descriptor,
        new java.lang.String[] { "ExpirationTimeMs", "FileId", "AccessMode", "User", "KeyId", });
    internal_static_alluxio_proto_security_Capability_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alluxio_proto_security_Capability_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alluxio_proto_security_Capability_descriptor,
        new java.lang.String[] { "Content", "Authenticator", "KeyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
